services:
  postgres:
    image: postgres:16-alpine
    container_name: leitor_dados_pdf_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: datachart
      POSTGRES_PASSWORD: datachart123
      POSTGRES_DB: leitor_dados_pdf
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
